# Generated by Django 3.0.2 on 2020-02-04 15:31

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200204_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='id',
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(default=data.models.pkgen, max_length=5, primary_key=True, serialize=False),
        ),
    ]
