# Generated by Django 3.0.2 on 2020-02-04 15:48

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200204_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(default=data.models.pkgen, max_length=6, primary_key=True, serialize=False),
        ),
    ]
